const formats = {
    "ingFormat":
    {
        "name":"ing-name",
        "is-it-jain":true,
        "not-jain-reason":"Reason",
        "is-it-vegan":true,
        "not-vegan-reason":"Reason",
        "is-it-vegitarian":true,
        "not-vegitarian-reason":"Reason",
        "allowed-on-tithi":true,
        "not-tithi-reason":"Reason",
        "status":"New/Review/Approved"
    },
    "itemFormat":{
        "data":{
            "brands":["brandName1","brandName2"],
            "item":"itemName",
            "is-it-jain":true,
            "reason-jain":"Reason",
            "is-it-vegan":true,
            "reason-vegan":"Reason",
            "is-it-vegitarian":true,
            "reason-vegitarian":"Reason",
            "is-it-tithi":true,
            "reason-tithi":"Reason",
            "ingredients":["ings"],
            "images":["imageURL"]
        },
        "barcode":"barcode number",
        "catagories":["catagory1","catagory2"]
    }
}